# Generated by Django 5.0 on 2026-04-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_code', models.CharField(max_length=32, unique=True, verbose_name='设备编码')),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('device_type', models.CharField(max_length=32, verbose_name='设备类型')),
                ('status', models.CharField(default='offline', max_length=24, verbose_name='设备状态')),
                ('online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
            ],
            options={
                'verbose_name': '设备台账',
                'verbose_name_plural': '设备台账',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_code', models.CharField(max_length=32, unique=True, verbose_name='任务编号')),
                ('image_name', models.CharField(max_length=128, verbose_name='原始文件名')),
                ('stored_path', models.CharField(blank=True, max_length=255, verbose_name='存储路径')),
                ('plot_code', models.CharField(blank=True, max_length=32, verbose_name='地块编号')),
                ('disease_name', models.CharField(blank=True, max_length=64, verbose_name='识别结果')),
                ('confidence', models.FloatField(default=0, verbose_name='置信度')),
                ('severity', models.CharField(blank=True, max_length=24, verbose_name='风险等级')),
                ('status', models.CharField(default='completed', max_length=24, verbose_name='任务状态')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='结果详情')),
            ],
            options={
                'verbose_name': '病虫害检测记录',
                'verbose_name_plural': '病虫害检测记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrchardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('block_code', models.CharField(max_length=32, unique=True, verbose_name='地块编号')),
                ('name', models.CharField(max_length=64, verbose_name='地块名称')),
                ('area_mu', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='面积(亩)')),
                ('growth_stage', models.CharField(blank=True, max_length=32, verbose_name='生长阶段')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
            ],
            options={
                'verbose_name': '园区地块',
                'verbose_name_plural': '园区地块',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan_code', models.CharField(max_length=32, unique=True, verbose_name='策略编号')),
                ('block_code', models.CharField(max_length=32, verbose_name='地块编号')),
                ('status', models.CharField(default='draft', max_length=24, verbose_name='状态')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='执行日期')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='策略内容')),
            ],
            options={
                'verbose_name': '水肥处方',
                'verbose_name_plural': '水肥处方',
            },
        ),
    ]
