# Generated by Django 5.0 on 2026-04-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=40, unique=True, verbose_name='策略编号')),
                ('block_code', models.CharField(max_length=32, verbose_name='地块编号')),
                ('block_name', models.CharField(max_length=100, verbose_name='地块名称')),
                ('growth_summary', models.CharField(max_length=255, verbose_name='长势摘要')),
                ('risk_summary', models.CharField(max_length=255, verbose_name='风险摘要')),
                ('irrigation_amount', models.FloatField(default=0, verbose_name='建议灌溉量(m3)')),
                ('fertilizer_amount', models.FloatField(default=0, verbose_name='建议施肥量(kg/亩)')),
                ('execution_window', models.CharField(max_length=64, verbose_name='执行时段建议')),
                ('prescription_grade', models.CharField(max_length=16, verbose_name='处方等级')),
                ('status', models.CharField(default='待下发', max_length=20, verbose_name='状态')),
                ('source_mode', models.CharField(default='mock', max_length=20, verbose_name='生成模式')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='扩展负载')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '决策策略',
                'verbose_name_plural': '决策策略',
                'ordering': ['-created_at'],
            },
        ),
    ]
