# Generated by Django 5.0 on 2026-04-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=32, unique=True, verbose_name='任务编号')),
                ('image_name', models.CharField(max_length=255, verbose_name='原始图片名称')),
                ('stored_path', models.CharField(max_length=255, verbose_name='存储路径')),
                ('diagnosis_name', models.CharField(blank=True, max_length=100, verbose_name='疑似病虫害名称')),
                ('confidence', models.FloatField(default=0, verbose_name='置信度')),
                ('risk_level', models.CharField(blank=True, max_length=20, verbose_name='风险等级')),
                ('status', models.CharField(default='completed', max_length=20, verbose_name='任务状态')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='建议措施')),
                ('overlay_boxes', models.JSONField(blank=True, default=list, verbose_name='标注框')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='完整结果')),
                ('inference_mode', models.CharField(default='mock', max_length=20, verbose_name='推理模式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '病虫害诊断任务',
                'verbose_name_plural': '病虫害诊断任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
